#!/bin/sh

# create a pre-commit virtual environment if it doesn't exist
python3 -m venv pre-commit-env

# activate the venv
source pre-commit-env/bin/activate
call pre-commit-env/Scripts/activate.bat

# install the pinned version of black if needed
pip install click==8.0.2
pip install black==21.12b0
python3 -m black .

pip install  isort==5.10.1
python3 -m isort .
### end ###