name: Add 'needs-documentation' Label to Associated Pull Requests

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  apply_label:
    runs-on: ubuntu-latest
    steps:
      # Set up Python 3.8 and install PyGithub
      - name: Set up Python and Install Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install PyGithub
        run: pip install PyGithub

      # Apply the 'needs-documentation' label to any associated pull requests if the issue has the 'needs-documentation' label
      - name: Apply 'needs-documentation' Label to Associated Pull Requests
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.WORKFLOW_APPLY_LABEL }}
        run: |
          python - <<EOF
          import os
          import json
          from github import Github

          # Create a PyGithub object using the GITHUB_TOKEN
          secret = os.environ["PERSONAL_ACCESS_TOKEN"]
          print('secret: ' + secret)
          g = Github(secret)

          # Get the repository object for the current repository
          repo = g.get_repo(os.environ["GITHUB_REPOSITORY"])

          # Load the event payload from the GITHUB_EVENT_PATH environment variable
          event_path = os.environ["GITHUB_EVENT_PATH"]
          event = {}
          if os.path.exists(event_path):
              with open(event_path, "r") as f:
                  event = json.load(f)
          print("Event: " + str(event))

          # Check if the event corresponds to an issue
          if "issue" in event:
              print("Event corresponds to an issue")
              issue_number = event["issue"]["number"]

              # Check if the issue has the 'needs-documentation' label
              if "needs-documentation" in [label.name for label in repo.get_issue(issue_number).labels]:
                  print(f"Issue #{issue_number} has 'needs-documentation' label")

                  # Get the pull requests associated with the issue
                  pull_requests = repo.get_pulls(state="open", sort="created", direction="desc")
                  print(f"Pull requests: {pull_requests}")
                  for pull in pull_requests:
                      if issue_number in [issue.number for issue in pull.get_issues()]:
                          # Apply the 'needs-documentation' label to the pull request
                          pull.add_to_labels("needs-documentation")
                          print(f"Applied 'needs-documentation' label to pull request #{pull.number}")
              else:
                  print(f"Issue #{issue_number} does not have 'needs-documentation' label")
          else:
              print("Event does not correspond to an issue")
          EOF
