name: Format code using black and isort
# modified from https://towardsdatascience.com/black-with-git-hub-actions-4ffc5c61b5fe

on:
  push:
    branches: [ master ]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code with black 
        run: |
          pip install black==21.12b0
          black .
      - name: Format code with isort
        run: |
          pip install  isort==5.10.1
          isort .
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Format code with black and sort imports with isort"
          add: "."
          branch: ${{ github.ref }}